### ISSUE TITLE
Training Dataset

### ISSUE THREAD

**Issue by ldkong1205** [ltp1995/GCAGC-CVPR2020#3]
Hi Tengpeng, the training dataset COCO-SEG that you share in the Readme cannot be unzipped. Can you check it? Thank you very much.

**Comment by ltp1995** [comment]
> Hi Tengpeng, the training dataset COCO-SEG that you share in the Readme cannot be unzipped. Can you check it? Thank you very much.

Thanks for your attention, i have re-uploaded the training datasets. Note that i split the images into three subfolders due to storage limits.

**Comment by ldkong1205** [comment]
> > Hi Tengpeng, the training dataset COCO-SEG that you share in the Readme cannot be unzipped. Can you check it? Thank you very much.
> 
> Thanks for your attention, i have re-uploaded the training datasets. Note that i split the images into three subfolders due to storage limits.

Got it. Thank you very much.
