### ISSUE TITLE
Where is the training code

### ISSUE THREAD

**Issue by KimKeepLearning** [ltp1995/GCAGC-CVPR2020#4]
I think this work is very impressive and your clear declaration inspired me a lot. But I got some trouble when I try to implement the training part of the algorithms. Could you release the training code?  I hope to see the details.

**Comment by ltp1995** [comment]
> I think this work is very impressive and your clear declaration inspired me a lot. But I got some trouble when I try to implement the training part of the algorithms. Could you release the training code? I hope to see the details.
Thanks for your attention of our work, now we do not plan to release the source training code.  However, more detailed training files can be shared if you can provide your email address.

**Comment by ltp1995** [comment]
> I think this work is very impressive and your clear declaration inspired me a lot. But I got some trouble when I try to implement the training part of the algorithms. Could you release the training code? I hope to see the details.

Thanks for your attention of our work, now we do not plan to release the source training code. However, more detailed training files can be shared if you can provide your email address.

**Comment by KimKeepLearning** [comment]
> > I think this work is very impressive and your clear declaration inspired me a lot. But I got some trouble when I try to implement the training part of the algorithms. Could you release the training code? I hope to see the details.
> 
> Thanks for your attention of our work, now we do not plan to release the source training code. However, more detailed training files can be shared if you can provide your email address.

Thanks a lot! My email address is yhuang@stu.xmu.edu.cn

**Comment by jjb202** [comment]
Thanks a lot! My email address is szpeng@stu.xmu.edu.cn.
I want your code too. thanks again!

**Comment by jonwomack** [comment]
I would like your training code as well! jwomack30@gatech.edu

**Comment by MaoYuxin25** [comment]
hello, If it is convenient for you, can you provide the training code, thank you very much. My email is maoyuxin@mail.nwpu.edu.cn
