### ISSUE TITLE
About the iCoseg dataset

### ISSUE THREAD

**Issue by jjb202** [ltp1995/GCAGC-CVPR2020#5]
Hi, I would like to know how the iCoseg dataset of 38 sets of 643 images is divided between the training and test sets.

**Comment by ltp1995** [comment]
> Hi, I would like to know how the iCoseg dataset of 38 sets of 643 images is divided between the training and test sets.

Actually, our model is trained on the COCO2017 dataset, which contains 200K training images. And all images in other datasets (e.g. iCoseg, Cosal2015, COSOD3K) are used as test sets.
