### ISSUE TITLE
test.py does not run.

### ISSUE THREAD

**Issue by Carlisle-Liu** [ltp1995/GCAGC-CVPR2020#6]
Hi authors,

I have tried to run your test.py file. However, it cannot load the pre-trained model. The error messages are as below. Could you please let me know what I need to change to make it work.

Thank you.

Traceback (most recent call last):
  File "test.py", line 104, in <module>
    test(gpu_id, model_path, val_root, val_datapath, True, save_root_path, 5, 224, 'image', ['.jpg', '.jpg', '.jpg'], ['.png', '.png', '.png'])
  File "test.py", line 17, in test
    net.load_state_dict(net_dict)
  File "/students/u6617221/.conda/envs/CoSOD-DPT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1224, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Model2:
        Unexpected key(s) in state_dict: "t.prnet.conv1.weight".

**Comment by ltp1995** [comment]
> Hi authors,
> 
> I have tried to run your test.py file. However, it cannot load the pre-trained model. The error messages are as below. Could you please let me know what I need to change to make it work.
> 
> Thank you.
> 
> Traceback (most recent call last): File "test.py", line 104, in test(gpu_id, model_path, val_root, val_datapath, True, save_root_path, 5, 224, 'image', ['.jpg', '.jpg', '.jpg'], ['.png', '.png', '.png']) File "test.py", line 17, in test net.load_state_dict(net_dict) File "/students/u6617221/.conda/envs/CoSOD-DPT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1224, in load_state_dict self.**class**.**name**, "\n\t".join(error_msgs))) RuntimeError: Error(s) in loading state_dict for Model2: Unexpected key(s) in state_dict: "t.prnet.conv1.weight".

Sorry for my late reply, it seems that the pretrained parameters are loaded in a wrong way! Maybe you should uncomment the line 11 and comment the line12~17 in test.py! Hope it can be helpful.

**Comment by Carlisle-Liu** [comment]
Thank you for your reply.
